# Generated by Django 5.0.2 on 2024-02-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_edu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('indicator', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('indicator', models.CharField(max_length=255)),
                ('percentage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
